---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="centos" tag="7"
    - image="debian" tag="latest"
    - image="debian" tag="bullseye"
    - image="fedora" tag="31"
    - image="fedora" tag="latest"
    - image="ubuntu" tag="latest"
    - image="ubuntu" tag="bionic"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "bW4M2mWcfGm2IbDpzwhglApcbTDWujFhh2XkPsTCSPzJq2aMaxPW9VCEV9r18mi611n7i0GjJQS2PUQOIKFQfF5ugq0oSHWKn/i4DRvCEgFdBVNq7DwYkVK9e5+s8I+O9a7epp+zZK45sgWkIRln3rM2KzR93iGP6WwavsAltCTwtK/27Qpp5ppHYYe8gzuwpcnS/awbDYn7cIPE1ufl+Fu53HzIlpxbj3eFE/No7DrhpTEW/XuMYqJoJl3kgvIMJ4YTjivUyjm0HaHmSRgt8wvIXkIpCpRM6ZwfYMK0S0QwqyyZh/LHI1KV89wZYRKn9o4eeEiiqLegOnBWXakq9GRyqJVYuCkEDzPS8kEfp1fuJHh63z0kY+MHbtRpgS4ZeGBalu4Tv0oW6MTQ6txyqYTdQhmUPobSVawrMp7FUoquAbFlXZcf1V6sPalUKb1RmZl0ZIB/w7ReBEmubuFck2b0JnusGux2ba+h4Pn84y7BWBCQOB4oLThJejQE+86nEdZBJW33H1j/2gx4/r+ZoKSUsmJV1oCK83RwQmjt9ZshetXXQ5boXY2Uq2NDcYNNJX97PtXc7MZQzQlpqYaYpLnMJ6t29+FvTDHrdIQj6OXDpItJwwdA0562Z6/j/lHjQlm3dUrT53LEMf4DvAYIN3+f+7oF5QZpHmGOGu+yoGY="
  email: false
