---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="centos" tag="7"
    - image="debian" tag="latest"
    - image="debian" tag="bullseye"
    - image="fedora" tag="31"
    - image="fedora" tag="latest"
    - image="ubuntu" tag="latest"
    - image="ubuntu" tag="bionic"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "DhsIB5Y4Vvv1DdGyzrmwZk/qSBQL5+B/ISmu2FU/0EgqN8qJ3cnk2CwMxpaJygutQDf4QCVcGj58rsj9yZWHf3KHDG/bVB8b3+8WSsxqh6e6/EkCiDUuCCp55O1Hk5inw0xeyJsI/u3vnM9sSlFygkjcjd4AlfB7BN7UM7WhI8O8NPf77s6/r/S8fqmf00wSdEMfDgh/z0Xs4LzNRE+4PGg1oIkhLbqbEUIn0vHW8pLg8ocuaB86duRY1DR2KcMKRszA3zeWqH2AX1D8HkXz3qer5y2VYEwXANKTUpFVTtM/mLrzBPjnfAkK1Yg1wgxh3PMCYO2XBe0RMo7OCPvS/RDEgQeKl+KoQvWj//WbHtUTgjDhmVFYipDPuR2uAjwXS+Z1u9RDyHS7ihBxzwNQlageaNn13OUBROTA6AQ0F1Wj5nR1H6rWB08U8TJYPscNapnSYK6jOiWYfpSCU6EkcZD3b24L7lV9LbuVC9vjju4Zea34vsO+4Q5hm39JZn+xn1ECgPjIZtPJB4E/pZb+E+/N0z/R30VvwYRENnj1wesM0vJcQwUoHv47ulKfULd5M2ucHHsYmQ4hx4ehBxv1nAb5D7X4d6PmbilxZeSCuqcotIyKUYFoEcrwiDdSQRgSOQzo+IibxU10J3P2oey3/7uZyyNOX00ztgRm2bp7r4M="
  email: false
